version: '3.8'

services:
  smart-upload:
    image: smart-upload-app:latest
    container_name: smart-upload-container
    ports:
      - "5000:5000"
    volumes:
      - ./input_files:/app/input_files
      - ./output_images:/app/output_images
    env_file:
      - .env
    restart: unless-stopped
